const categories = [
	{
		_id: '5dffd0cead0bac0370b5122c',
		name: 'Meat & Fish',
		__v: 0,
	},
	{
		_id: '5dffd0cead0bac0370b5122d',
		name: 'Wine & Drinks',
		__v: 0,
	},
	{
		_id: '5dffd0cead0bac0370b5122a',
		name: 'Milk & Eggs',
		__v: 0,
	},
	{
		_id: '5dffd0cead0bac0370b5122b',
		name: 'Vegetable & Fruits',
		__v: 0,
	},
	{
		_id: '5e00fb4dcff61a4f1ccfdd3e',
		name: 'Grains & Nuts',
		__v: 0,
	},
	{
		_id: '5e00fb5acff61a4f1ccfdd40',
		name: 'Fish & Seafood',
		__v: 0,
	},
	{
		_id: '5e00fb7ccff61a4f1ccfdd41',
		name: 'vegan',
		__v: 0,
	},
	{
		_id: '5e00fb83cff61a4f1ccfdd42',
		name: 'canned',
		__v: 0,
	},
	{
		_id: '5e00fb8fcff61a4f1ccfdd43',
		name: 'nuts',
		__v: 0,
	},
];

const veggies = [
	'artichoke',
	'aubergine',
	'eggplant',
	'asparagus',
	'legumes',
	'alfalfa sprouts',
	'azuki beans ',
	'adzuki',
	'bean sprouts',
	'black beans',
	'black-eyed peas',
	'borlotti bean',
	'broad beans',
	'chickpeas',
	'garbanzos',
	'ceci beans',
	'green beans',
	'kidney beans',
	'lentils',
	'lima beans',
	'Butter bean',
	'mung beans',
	'navy beans',
	'peanuts',
	'pinto beans',
	'runner beans',
	'split peas',
	'soy beans',
	'peas',
	'mangetout',
	'snap peas',
	'broccoflower',
	'broccoli',
	'calabrese',
	'brussels sprouts',
	'cabbage',
	'kohlrabi',
	'Savoy Cabbage',
	'Red Cabbage',
	'Pointed',
	'Sweetheart',
	'Cabbage',
	'cauliflower',
	'celery',
	'endive',
	'fiddleheads',
	'frisee',
	'fennel',
	'greens',
	'bok choy',
	'chard',
	'beet greens',
	'collard greens',
	'kale',
	'mustard greens',
	'spinach',
	'herbs and spices',
	'anise',
	'basil',
	'caraway',
	'coriander',
	'also known as cilantro',
	'chamomile',
	'dill',
	'fennel',
	'lavender',
	'Cymbopogon',
	'also known',
	'lemongrass',
	'marjoram',
	'oregano',
	'parsley',
	'rosemary',
	'sage',
	'thyme',
	'lettuce',
	'arugula',
	'mushrooms',
	'nettles',
	'New Zealand spinach',
	'okra',
	'onions',
	'Chives',
	'Garlic',
	'Leek',
	'onion',
	'shallot',
	'scallion',
	'spring onion UK',
	'green onion US',
	'peppers',
	'bell pepper',
	'chili pepper',
	'Jalapeño',
	'Habanero',
	'Paprika',
	'Tabasco pepper',
	'Cayenne pepper',
	'radicchio',
	'rhubarb',
	'root vegetables',
	'beetroot',
	'Beet',
	'mangel wurzel',
	'carrot',
	'celeriac',
	'corms',
	'eddoe',
	'konjac',
	'taro',
	'water chestnut',
	'ginger',
	'parsnip',
	'rutabaga',
	'radish',
	'wasabi',
	'horseradish',
	'white radish',
	'daikon',
	'tubers',
	'jicama',
	'jerusalem artichoke',
	'potato',
	'sweet potato',
	'yam',
	'turnip',
	'salsify',
	'skirret',
	'sweetcorn',
	'topinambur',
	'squashes',
	'acorn squash',
	'bitter melon',
	'butternut squash',
	'banana squash',
	'courgette ',
	'Zucchini',
	'cucumber',
	'delicata',
	'gem squash',
	'hubbard squash',
	'marrow ',
	'Squash',
	'spaghetti squash',
	'tat soi',
	'tomato',
	'watercress',
];

const itemTemplate = { name: '', price: 0.0, amount: 100, categoryId: '', imgUrl: '' };

maxItems = 200;

const productArray = [];

for (let i = 0; i < veggies.length; i++) {
	const categoryIndex = Math.floor(Math.random() * categories.length);
	const categoryID = categories[categoryIndex]._id;

	const price = Number(`${getRandomInt(1, 75)}.${getRandomInt(10, 99)}`);

	const product = {
		name: veggies[i],
		price: price,
		amount: getRandomInt(20, 250),
		category: categoryID,
		imgUrl: 'http://localhost:3000/public/images/pickleRick.png',
	};

	productArray.push(product);
}

console.log('TCL: productArray', JSON.stringify(productArray));

function getRandomInt(min, max) {
	min = Math.ceil(min);
	max = Math.floor(max);
	return Math.floor(Math.random() * (max - min + 1)) + min;
}
